export const TRY_AUTH = "TRY_AUTH";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";

export const SET_PASSWORD_RECOVERY_LOADING = "SET_PASSWORD_RECOVERY_LOADING";
export const SET_PASSWORD_RECOVERY_SUCCESS = "SET_PASSWORD_RECOVERY_SUCCESS";

export const SET_CREATE_ACCOUNT_SUCCESS = "SET_CREATE_ACCOUNT_SUCCESS";


